# Header
menu:
  Home: /
  Archives: /archives
  Quotes: /Quotes
  Repositories: https://github.com/bkarr?tab=repositories
  About: /About
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
